"""add collection and category to products

Revision ID: f8967ad98ea0
Revises: e6a35a7c000e
Create Date: 2026-06-13 20:48:37.312628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8967ad98ea0'
down_revision = 'e6a35a7c000e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('collection')

    # ### end Alembic commands ###
